PREFIX api: <http://www.aekos.org.au/api/1.0#>

SELECT ?speciesName ?dwr ?loc
WHERE {
  ?dwr a api:DarwinCoreRecord .
  {?dwr api:scientificName ?speciesName .}
  UNION
  {?dwr api:taxonRemarks ?speciesName .}
  ?dwr api:eventDate ?eventDate .
  ?dwr api:locationID ?locationID .
  ?loc a api:LocationVisit .
  ?loc api:locationID ?locationID .
  ?loc api:eventDate ?eventDate .
}
