PREFIX api: <http://www.aekos.org.au/api/1.0#>

SELECT *
WHERE {
  {
	  ?s a api:DarwinCoreRecord .
	  ?s api:scientificName ?scientificName .
#OFF  VALUES ?scientificName { %SPECIES_NAMES_PLACEHOLDER% } .
  }
  UNION {
	  ?s a api:DarwinCoreRecord .
	  ?s api:taxonRemarks ?taxonRemarks .
#OFF  VALUES ?taxonRemarks { %SPECIES_NAMES_PLACEHOLDER% }
  }
  ?s api:decimalLatitude ?decimalLatitude .
  ?s api:decimalLongitude ?decimalLongitude .
  ?s api:eventDate ?eventDate .
  ?s api:geodeticDatum ?geodeticDatum .
  ?s api:individualCount ?individualCount .
  ?s api:locationID ?locationID .
  ?s api:year ?year .
  ?s api:month ?month .
  ?s api:samplingProtocol ?samplingProtocol .
  ?s api:samplingProtocolEntity ?datasetDesc .
  ?datasetDesc api:bibliographicCitation ?bibliographicCitation .
}
ORDER BY ?s
OFFSET %OFFSET_PLACEHOLDER%
LIMIT %LIMIT_PLACEHOLDER%