PREFIX api: <http://www.aekos.org.au/api/1.0#>

SELECT (count(DISTINCT ?s) as ?count)
WHERE {
  ?s a api:DarwinCoreRecord .
  ?s api:scientificName ?scientificName .
  VALUES ?scientificName { %SPECIES_NAMES_PLACEHOLDER% } .
  ?s api:trait/api:name ?traitName .
  VALUES ?traitName { %TRAIT_NAME_PLACEHOLDER% } .
}
