PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aekos: <http://www.aekos.org.au/ontology/1.0.0#>
PREFIX api: <http://www.aekos.org.au/api/1.0#>

# Gets the easy (1:1) part of the Darwin Core + traits dataset: the species records. Traits will come later
SELECT
	?id
	(?og as ?rdfSubject)
	(?g as ?rdfGraph)
	?locationID
	?scientificName
	?taxonRemarks
	?individualCount
WHERE { GRAPH ?g {
   ?og a ?ogType .
   VALUES ?ogType {
#      aekos:ORGANISMGROUP # Left out on purpose (as instructed by Matt)
    aekos:INDIVIDUALORGANISM
    aekos:SPECIESORGANISMGROUP
  }
  # scientificName
  OPTIONAL {?og aekos:determinedspeciesconcept/aekos:species/aekos:name ?determinedSpeciesNameValue . } #OFF4dewnr_bdbsa
  OPTIONAL {?og aekos:determinedspeciesconcept/aekos:species/aekos:namewithoutauthorship ?determinedSpeciesNameWOAuthorshipValue . }
  OPTIONAL {?og aekos:determinedspeciesconcept/aekos:species/aekos:title ?determinedSpeciesTitleValue . }
  OPTIONAL {?og aekos:determinedspeciesconcept/aekos:species/aekos:namewithauthorship ?determinedSpeciesNameWAuthorshipValue . }
  OPTIONAL {?og aekos:fieldspeciesconcept/aekos:species/aekos:name ?fieldSpeciesNameValue . }
  OPTIONAL {?og aekos:fieldspeciesconcept/aekos:species/aekos:namewithoutauthorship ?fieldSpeciesNameWOAuthorshipValue . }
  OPTIONAL {?og aekos:fieldspeciesconcept/aekos:species/aekos:namewithauthorship ?fieldSpeciesNameWAuthorshipValue . }
  BIND (COALESCE(
        ?determinedSpeciesNameWAuthorshipValue,
        ?fieldSpeciesNameWAuthorshipValue,
        ?determinedSpeciesNameValue, #OFF4dewnr_bdbsa
        ?determinedSpeciesNameWOAuthorshipValue,
        ?determinedSpeciesTitleValue,
        ?fieldSpeciesNameValue,
        ?fieldSpeciesNameWOAuthorshipValue) as ?scientificNameTemp) .
  BIND (REPLACE(REPLACE(?scientificNameTemp,"^\\s*",""), "\\s*$","") as ?scientificName) .
  # taxonRemarks
  OPTIONAL {?og aekos:fieldspeciesconcept/aekos:commentary ?fieldSpeciesConceptCommentary . }
  OPTIONAL {?og aekos:determinedspeciesconcept/aekos:commentary ?determinedSpeciesConceptCommentary . }
  BIND (COALESCE(
        ?determinedSpeciesConceptCommentary,
        ?fieldSpeciesConceptCommentary) as ?taxonRemarksTemp) .
  # make ?taxonRemarks empty if we already have a scientificName so we don't get output in the CONSTRUCT
  # note: assumes that ?nothing isn't bound to anything
  BIND (IF(BOUND(?scientificName), ?nothing, REPLACE(REPLACE(?taxonRemarksTemp,"^\\s*",""), "\\s*$","")) as ?taxonRemarks) .
  FILTER(bound(?scientificName) || bound(?taxonRemarks)) .
  # get StudyLocationSubgraph ref
  ?og ^rdfs:member/^aekos:observeditems/^rdfs:member/^aekos:views ?slsg .
  # study location IDs
  ?slsg aekos:aekoslocationidentifier ?locationID .
  # individualCount
  OPTIONAL {?og aekos:absoluteabundance/aekos:value ?absoluteAbundance . }
  BIND (COALESCE(?absoluteAbundance, 1) as ?individualCount) .
  # make an ID for this record
  BIND (STRUUID() as ?id) .
}}